package com.assignment.TC.controller;

import java.time.Instant;
import java.util.List;

//import javax.validation.Valid;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.assignment.TC.Model.Address;
import com.assignment.TC.Model.Trainingcenter;
import com.assignment.TC.Repo.TrainingcenterRepo;

@RestController
@RequestMapping("/v1/api")
public class Controller {

	@Autowired
	TrainingcenterRepo trepo;

	@GetMapping("/hi")
	public String returnstring1() {
		return " Hi?";
	}
	/*public List<Trainingcenter> Getdata() {
		List<Trainingcenter> Traininglist = trepo.findAll(); // retrieving data from repository
		return Traininglist;
	}

	@PostMapping("/postdata")
	public Trainingcenter Postdata(@RequestBody @Valid Trainingcenter trainingobj) {
		trainingobj.setCreatedon(Instant.now()); // setting the value of Epoch time generated by System
		return trepo.save(trainingobj); // returns the newly saved TraningCenter information in json format
	}
*/
}
